# Generated by Django 6.0 on 2025-12-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('input_text', models.TextField()),
                ('summary_text', models.TextField()),
                ('tokens_requested', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
