# Generated by Django 6.0 on 2025-12-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(choices=[('MULTIPLE_FACE', 'Multiple faces detected'), ('NO_FACE', 'No face detected'), ('EYE_OFF_SCREEN', 'Eyes not on screen'), ('LIP_MOVEMENT', 'Suspicious lip movement'), ('DEVICE', 'Mobile/Smartwatch detected')], max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('details', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='exams.examsession')),
            ],
        ),
    ]
