# Generated by Django 6.0 on 2025-12-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0002_proctoranomaly_delete_anomaly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoranomaly',
            name='image',
        ),
    ]
